- name: Preconfig
  hosts: demo
  tasks:
    - name: Docker install
      block:
        - name: Adding universe repository
          apt_repository:
            repo: deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe
            state: present

        - name: Install additional packages for docker
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: true
            cache_valid_time: 86400

        - name: Adding docker key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg
            state: present

        - name: Install stable repository
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: true
            filename: docker

        - name: Install docker
          apt:
            name: docker-ce
            update-cache: true

        - name: Checks that docker installed
          service:
            name: docker
            state: restarted
            enabled: true
      become: true

    - name: Install docker-compose
      block:
        - name: Get last version docler-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page
        - name: Insall docker-compose
          get_url:
            url: https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: 0755
      become: true

    - name: Finishing install
      block:
        - name: Adding user to group
          user:
            name: "{{ansible_user}}"
            groups: docker
            append: true

        - name: Rebooting
          reboot:
      become: true
